In [1]:
import numpy as np


Elementwise Operations


In [2]:
#multiplication using the scalers

In [3]:
a = np.array([1,2,3,4,])
a**2

array([ 1,  4,  9, 16])

In [4]:
b =np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [5]:
a*b

array([2., 4., 6., 8.])

In [6]:
#matrix multiplication

c = np.diag([1,2,3,4,5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [7]:
 c*c

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [8]:
print(c*c)
print('*****************')
print(c.dot(c))

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
*****************
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


In [9]:
a =np.array([1,2,3,4])
b =np.array([5,6,7,8])
a==b

array([False, False, False, False])

In [10]:
a > b

array([False, False, False, False])

In [11]:
a =np.array([1,2,3,4])
b =np.array([5,6,7,8])
c= np.array([7,3,1,2])
d=np.array([1,2,3,4])
np.array_equal(a,c)

False

In [12]:
np.array_equal(a,d)

True

In [13]:
a = np.array([0,0,1,0],dtype =bool)
b = np.array([1,1,0,0],dtype =bool),
np.logical_or(a,b)

array([[ True,  True,  True, False]])

In [14]:
np.logical_and(a,b) #kisi ek me bhi 0 raha toh wo false

array([[False, False, False, False]])

In [15]:
#Transcendental Functions
#A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. ... A list is the Python equivalent of an array, but is resizeable and can contain elements of different types
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [16]:
print(np.sin(a));print(np.log(a));print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [18]:
#WE CAN NOT ADD ARRAYS OF DIFFERENT SIZES
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [19]:
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [21]:
#basic reductions
A

array([0, 1, 2, 3, 4])

In [22]:
np.sum(A)

10

In [23]:
x= np.array(([1,2],[3,4]))
x

array([[1, 2],
       [3, 4]])

In [26]:
#sum by using the rows and columns
x.sum(axis =0) #it will add column wise



array([4, 6])

In [27]:
x.sum(axis=1) #adding values rowwise

array([3, 7])

In [28]:
x = np.array([1,10,2])
x

array([ 1, 10,  2])

In [29]:
x.min()

1

In [30]:
x.max()

10

In [31]:
x.argmin() #index of minimm element

0

In [32]:
x.argmax() #Index of maximum element\\\\\


1

In [35]:
#Logical operations
np.all([True,True,False]) #np.all it will take false element in the array , if anyone if false it will retune as a false 

False

In [36]:
np.any([True,False,False]) #np any me if any of the element in the array is true it will return as true 

True

In [39]:
a= np.zeros((40,40))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
np.any(a!=0) #count any of the element is not equal to zero

False

In [44]:
np.all(a == a)

True

In [46]:
a =np.array([1,2,3,4])
b = np.array([4,5,6,7])
c =np.array([3,2,1,4])
((a<=b))&(b<=c).all()

array([False, False, False, False])

In [47]:
a.mean()

2.5

In [48]:
np.median(a)


2.5

In [50]:

x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
np.median(y,axis = -1)

array([2., 5.])

In [51]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [53]:
data = np.loadtxt('population.txt')

In [54]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [61]:
data.std(axis=0)
populations = data [:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [62]:
populations.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [63]:
populations.std(axis =1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [65]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [67]:
np.argmax(populations,axis = 0)# zero for the column wise

array([3, 4, 0])

In [68]:
#to adding throught the broadcasting 
a = np.tile(np.arange(0,40,10),(3,1)) # it creates broadcasting functions
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [69]:
a=a.T

In [70]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [72]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [75]:
print(b.shape);print(b.ndim) # getting shape and dimension of a and b

(3,)
1


In [76]:
print(a.shape);print(a.ndim)

(4, 3)
2


In [77]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [89]:
# now creates broadcasting function which adds a new axis
a = np.arange(0,40,10)
a.shape
a

array([ 0, 10, 20, 30])

In [90]:
a =a[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [91]:
a.shape

(4, 1)

In [92]:
a=a[:,np.newaxis]
a

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [93]:
a.shape  #so that is how we can create the new axis 

(4, 1, 1)

In [96]:
print(a);print('***********');print(b);print('***********');print(a+b)

[[[ 0]]

 [[10]]

 [[20]]

 [[30]]]
***********
[0 1 2]
***********
[[[ 0  1  2]]

 [[10 11 12]]

 [[20 21 22]]

 [[30 31 32]]]


In [97]:
#Array shape manipulation ,Flatterning
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [99]:
a.ravel() ##Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed

array([1, 2, 3, 3, 4, 5])

In [103]:
a=a.T
a

array([[1, 2, 3],
       [3, 4, 5]])

In [104]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [105]:
a.T.ravel()

array([1, 3, 2, 4, 3, 5])

In [106]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [107]:
a.shape

(2, 3)

In [108]:
b=a.ravel()
b

array([1, 2, 3, 3, 4, 5])

In [109]:
b.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [110]:
b.reshape(2,3)

array([[1, 2, 3],
       [3, 4, 5]])

In [111]:
b

array([1, 2, 3, 3, 4, 5])

In [112]:
b= b.reshape(2,3)

In [113]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [114]:
b[0,1]=20
b

array([[ 1, 20,  3],
       [ 3,  4,  5]])

In [115]:
a

array([[ 1, 20,  3],
       [ 3,  4,  5]])

In [116]:
b

array([[ 1, 20,  3],
       [ 3,  4,  5]])

In [117]:
# above both have same details , lets check if both shares the same memory
np.shares_memory(a,b)

True

In [118]:
#now we will create both have different memory allocation
b=b.copy()

In [119]:
b

array([[ 1, 20,  3],
       [ 3,  4,  5]])

In [120]:
np.shares_memory(a,b)

False

Adding a Dimension

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [121]:
z = np.array([10,11,23])
z

array([10, 11, 23])

In [122]:
z.shape

(3,)

In [123]:
z[:,np.newaxis]

array([[10],
       [11],
       [23]])

In [124]:
#dimension shuffling
a = np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [127]:
a.reshape(4,3,2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [128]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [131]:
a= np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [139]:
#Resizing
a =np.arange(4)
a

array([0, 1, 2, 3])

In [142]:
a.resize((4,))
a

array([0, 1, 2, 3])

In [149]:
#sorting along on a axis:
a =np.arange(3)
a

array([0, 1, 2])

In [150]:
b=np.arange(3,6)

In [147]:
b

array([3, 4, 5])

In [152]:
#how to make two arrays in a single ;Use rangefunction to creta arrays