#numpy basics
#Package for the scientific computing in python, it is a python library provides nultidimensional array object, array contains
# integers ,floating pointes

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(np.arange(10))    

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
# IT is memory -fficient , and fast numerical operations
#python lists and time taken by that
list= range(1000)
%timeit (i**2 for i in list)

946 ns ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
# Above one is for the normal list now as for the numpy
list1 = np.arange(1000)
%timeit (list1**2)

4.14 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
#Creating of the arrays
a = np.array([1,2,3,4,6])
a

array([1, 2, 3, 4, 6])

In [5]:
a.ndim #It will show dimensions of that array


1

In [6]:
a.shape #(row,columns)


(5,)

In [7]:
#exsamples of the 2-d and the 3-d arrays
b = np.array([[1,2,3],[3,4,5]])
print(b)
print(b.ndim)
print(b.shape) #(rows,columns)
print(len(b)) # it will give the size of the first dimension

[[1 2 3]
 [3 4 5]]
2
(2, 3)
2


In [8]:
# for 3 d list 
c=  np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c #list > list

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
c.ndim

3

In [10]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c #3d example becomes cube

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
c.shape

(2, 2, 2)

In [12]:
len(c)

2

In [13]:
#Functions for creating the arrays

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(1,20,3) # Start , end before 20 , with the difference of 3
b

array([ 1,  4,  7, 10, 13, 16, 19])

In [15]:
#we also use linspace but there is a little bit differnce  last number gives number of points instead of the differnce in the linspace
b= np.linspace(1,20,3) #It will end on 20
b

array([ 1. , 10.5, 20. ])

In [16]:
#some common arrays
#creating array of ones
a = np.ones((3,3)) #here there is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
b = np.eye(3) #diagonally number is ones and zeroes elsewhere
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
c = np.eye(3,2)# (rows,columns)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
a = np.diag([1,3,2,3,4])
a

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [21]:
#Create array using random function.
a = np.random.rand(4)
a

array([0.69040255, 0.30142659, 0.04542263, 0.81705873])

In [22]:
a = np.random.randn(4)
a

array([ 0.44051109,  1.16054795,  0.99795269, -0.56188408])

In [23]:
#BASIC DATA TYEPS
a= np.arange(10)
a.dtype

dtype('int64')

In [24]:
a = np.arange(10,dtype = 'float64')
a


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:

d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [26]:
b = np.array([True, False, True, False])  #Boolean datatype



In [27]:
print(b.dtype)

bool




3. Indexing and Slicing
3.1 Indexing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):]

In [28]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [30]:
a = np.diag([1,2,3])
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [31]:
#assigning balues
a[2,1]= 6
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 6, 3]])

In [34]:
#slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[1:8:2] #start,end,difference

array([1, 3, 5, 7])

In [37]:
a[5:] #after 5

array([5, 6, 7, 8, 9])

In [45]:
a[5:] =np.arange(5)
a

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [46]:
a[5:] =10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [47]:
a = np.arange(10);a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
b= a[::2];b #means starting from zero, till the end having difference of 2

array([0, 2, 4, 6, 8])

In [50]:
#here a and b both using the same memmory to store the numbers
np.shares_memory(a,b)

True

In [51]:
#we can try to modify the memory
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [52]:
np.shares_memory(a,b)

True

In [53]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [54]:
#even after modify b , it will updated a because both shares the same memory


In [55]:
a = np.arange(10)
c =a[::2].copy() #  force a copy
c

array([0, 2, 4, 6, 8])

In [56]:
np.shares_memory(a,c)

False

In [57]:
# .copy creates  new memory allocation for the c


#Fancy INdexing -
NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.


In [59]:
a = np.random.randint(0,20,15)
a

array([14, 11, 15,  2, 10, 13,  5, 10,  0, 16,  4, 10, 13, 13, 19])

In [60]:
mask = ( a % 2 == 0)
mask

array([ True, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True, False, False, False])

In [61]:
a[mask]

array([14,  2, 10, 10,  0, 16,  4, 10])

In [62]:
#it's useful to assign a new value to a sub-array

In [64]:
#Indexing with a mask can be very useful to assign a new value to a sub-array:
a[mask] =-1
a

array([-1, 11, 15, -1, -1, 13,  5, -1, -1, -1, -1, -1, 13, 13, 19])

In [66]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
a[[2,3,4,5,5]]
#we can also assign new values 

array([20, 30, 40, 50, 50])